### ISSUE TITLE
libthai.so.0 missing

### ISSUE THREAD

**Issue by ghost** [Korkman/macemu-appimage-builder#18]
SheepShaver-x86_64.AppImage from d4659915c44ecafa026dc02ffe7b2c6d796fb651 has libthai.so.0 missing. This is pretty bad - AppImage, snap, flatpak and all those other Windows-solutions to Windows-problems were conceived specifically to combat this kind of issue... Please fix this. I had to track down `libthai` to `gentoo-zh` overlay and add 2 package keywords to get this working.

**Comment by ghost** [comment]
Thank you @Korkman :)

**Comment by Korkman** [comment]
I included libthai in the Dockerfile. A new build will be available soon.

**Comment by Korkman** [comment]
Build is complete. Can you verify this fixes the problem?

**Comment by ghost** [comment]
Yes. I confirm it's fixed. Thank you!
