### ISSUE TITLE
Illegal instruction while trying to run HoMM3 Complete Demo

### ISSUE THREAD

**Issue by ghost** [Korkman/macemu-appimage-builder#19]
Steps to reproduce:
1. Get a working OS9.
2. Download https://archive.org/download/heroes_3_complete_demo/heroes_3_complete_demo.sit
3. Install.
4. Run.
5. Click "new game". UPDATE: clicking "quit" also triggers the exact same error and message log.

SheepShaver hangs with the following message spamming the logs:
```
Illegal instruction at 5046d304, opcode = 0f040000
```

**Comment by Korkman** [comment]
Can confirm this happens on the Windows build, too, so it is an emulator bug. Nothing I can do here 🫤

**Comment by Korkman** [comment]
(there is a report of the demo working in SheepShaver on OS X, but I have no idea how old that report is and whether it ever worked on other builds, and if so, which build broke it)

**Comment by ghost** [comment]
Alright, thank you. Since this is not an issue with this build, I've taken it to upstream to https://github.com/cebix/macemu/issues/269
